package myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long money;
	
	private String name;

	public Account() {
	}

	@Override
	public String toString() {
		return "Account [money=" + money + ", name=" + name + "]";
	}

	public java.lang.Long getMoney() {
		return this.money;
	}

	public void setMoney(java.lang.Long money) {
		this.money = money;
	}

	public Account(java.lang.Long money, java.lang.String name) {
		this.money = money;
		this.name = name;
	}

}