package myteam.decision_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Counter2 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Counter2() {
    }




}