package myteam.decision_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Counter1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	
	private java.lang.String name;
	
	private int count;

	public Counter1() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Counter1(java.lang.String name, int count) {
		this.name = name;
		this.count = count;
	}
	
	@Override
	public String toString() {
		return "Counter [name=" + name + ", count=" + count + "]";
	}

}