package myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Counter implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private int count;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;

	public Counter() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	@Override
	public String toString() {
		return "Counter [name=" + name + ", count=" + count + "]";
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Counter(java.lang.String name, int count, java.lang.String id) {
		this.name = name;
		this.count = count;
		this.id = id;
	}

}